require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('range_operators', '0.1.0') do |p|
  p.description    = "A gem that adds range methods to Ruby's Range and Array classes. (Range#+, Range#-, Array#rangify, Array#intersection, Array#missing)"
  p.url            = "http://github.com/monocle/range_operators"
  p.author         = "monocle"
  p.email          = "frappez_2000@yahoo.com"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end
